1..15: Very severely underweight
15..16: severely underweight
16..18.5: Underweight
18.5..25: Normal (healthy weight)
25..30: Overweight
30..35: Obese Class I (Moderately obese)
35..40: Obese Class II (Severely obese)
40..100: Obese Class II (Severely obese)
